from fastapi import APIRouter, HTTPException, status
from fastapi.responses import StreamingResponse
from uuid import UUID
import io
import csv
from datetime import datetime

router = APIRouter()


@router.get("/{interview_id}/pdf")
async def get_report_pdf(interview_id: UUID):
    """Generate and download PDF report for an interview"""
    
    # In production, use reportlab or weasyprint to generate actual PDF
    # This is a placeholder that returns a text response
    
    pdf_content = f"""
    AI Interview Report
    ===================
    
    Interview ID: {interview_id}
    Generated: {datetime.utcnow().strftime('%Y-%m-%d %H:%M:%S')}
    
    Candidate: Sarah Chen
    Position: Senior Software Engineer
    Interview Date: 2024-01-15
    
    OVERALL SCORE: 7.8/10
    RECOMMENDATION: HIRE
    
    SCORE BREAKDOWN
    ---------------
    Technical Skills: 8.2
    Communication: 7.8
    Problem Solving: 8.0
    Leadership: 6.5
    Domain Knowledge: 7.5
    
    KEY STRENGTHS
    --------------
    - Strong system design skills
    - Clear communication
    - Real-world experience
    
    AREAS TO INVESTIGATE
    ---------------------
    - Leadership at scale
    - ML integration experience
    
    This report is auto-generated by AI Interview Platform.
    """
    
    # Return as text (in production, return actual PDF)
    return StreamingResponse(
        io.StringIO(pdf_content),
        media_type="text/plain",
        headers={
            "Content-Disposition": f"attachment; filename=interview_report_{interview_id}.txt"
        }
    )


@router.get("/{interview_id}/csv")
async def get_report_csv(interview_id: UUID):
    """Generate and download CSV report for an interview"""
    
    # Create CSV data
    csv_data = [
        ["Metric", "Value"],
        ["Interview ID", str(interview_id)],
        ["Candidate Name", "Sarah Chen"],
        ["Position", "Senior Software Engineer"],
        ["Overall Score", "7.8"],
        ["Technical Score", "8.2"],
        ["Communication Score", "7.8"],
        ["Problem Solving Score", "8.0"],
        ["Leadership Score", "6.5"],
        ["Recommendation", "HIRE"],
        ["Interview Duration (min)", "45"],
        ["Questions Asked", "12"],
        ["Report Generated", datetime.utcnow().strftime('%Y-%m-%d %H:%M:%S')],
    ]
    
    # Generate CSV string
    output = io.StringIO()
    writer = csv.writer(output)
    writer.writerows(csv_data)
    
    return StreamingResponse(
        io.StringIO(output.getvalue()),
        media_type="text/csv",
        headers={
            "Content-Disposition": f"attachment; filename=interview_report_{interview_id}.csv"
        }
    )


@router.get("/{interview_id}/summary")
async def get_report_summary(interview_id: UUID):
    """Get interview report summary"""
    
    return {
        "interview_id": str(interview_id),
        "candidate": {
            "name": "Sarah Chen",
            "email": "sarah.chen@example.com",
            "applied_position": "Senior Software Engineer"
        },
        "interview_details": {
            "date": "2024-01-15",
            "duration_minutes": 45,
            "questions_asked": 12,
            "mode": "video"
        },
        "scores": {
            "overall": 7.8,
            "technical": 8.2,
            "communication": 7.8,
            "problem_solving": 8.0,
            "leadership": 6.5,
            "domain_knowledge": 7.5
        },
        "recommendation": {
            "decision": "HIRE",
            "confidence": 0.85,
            "reasoning": "Strong candidate with solid technical skills"
        },
        "highlights": {
            "strengths": [
                "Excellent system design skills",
                "Clear and articulate communication",
                "Strong problem-solving approach"
            ],
            "concerns": [
                "Limited leadership experience at scale"
            ]
        },
        "transcript_available": True,
        "recording_available": True,
        "generated_at": datetime.utcnow().isoformat()
    }


@router.get("/{interview_id}/hiring-memo")
async def get_hiring_memo(interview_id: UUID):
    """Generate hiring memo for an interview"""
    
    return {
        "interview_id": str(interview_id),
        "memo": """
        HIRING MEMO
        ===========
        
        Candidate: Sarah Chen
        Position: Senior Software Engineer
        Interview Date: January 15, 2024
        
        SUMMARY
        -------
        Sarah demonstrated strong technical abilities during the interview,
        particularly in system design and problem-solving. She communicated
        her ideas clearly and provided specific examples from her experience
        at Google and Meta.
        
        STRENGTHS
        ----------
        • Strong system design skills with practical experience
        • Excellent communication - articulate and clear
        • Good understanding of distributed systems and scalability
        • Real-world experience with large-scale systems
        
        AREAS OF CONCERN
        -----------------
        • Limited experience with ML/AI technologies
        • Leadership experience primarily at team level, not org-wide
        
        RECOMMENDATION
        --------------
        I recommend moving forward with hiring Sarah for the Senior
        Software Engineer position. Her technical foundation is solid
        and she would be a great addition to the platform team.
        
        Follow-up recommended: Discuss leadership opportunities and
        interest in ML/AI projects during final round.
        
        Interviewer: [Recruiter Name]
        Date: January 15, 2024
        """.strip()
    }
